settings:
  digits: 3
  itemformat: markdown
  parent: MRS
  prefix: SRS
  sep: '-'

attributes:
  defaults:
    type: 'F'
    importance: "[1-5]"
    urgency: "[1-5]"
    release: "Beta"
    text: |
      # Title

      - Option 1: Description
      - Option 2: As a `<role>`, I want `<to perform this action>` so that `<I can accomplish this goal>`

      ### Rationale
      ...

      ### Acceptance criteria
      ...
    vm: 'Test (T), Review of design (R), Inspection (I), Analysis (A)'

  publish:
    - type
    - importance
    - urgency
    - vm
    - release
  
  reviewed:
    - type
    - importance
    - urgency
    - vm
    - release