# Warninglists covering public scanning services
# Selected by name, since warninglist IDs are MISP instance dependent
SCANNING_WARNINGLISTS = [
    "Alphastrike research IP Ranges Used for Scanning",
    "Alpha Strike Labs IP Ranges Used for Scanning",
    "Bufferover IP Ranges Used for Scanning",
    "Censys IP Ranges Used for Scanning",
    "Coalition signals intelligence IP Ranges Used for Scanning",
    "Cybergreen IP Ranges Used for Scanning",
    "Cyberresilience IP Ranges Used for Scanning",
    "Cypex IP Ranges Used for Scanning",
    "F6 IP Ranges Used for Scanning",
    "Internet census IP Ranges Used for Scanning",
    "Intrinsec IP Ranges Used for Scanning",
    "Ipinfo IP Ranges Used for Scanning",
    "Ipip IP Ranges Used for Scanning",
    "Modat IP Ranges Used for Scanning",
    "List of published IP address ranges for Modat Scanner",
    "Netsecscan IP Ranges Used for Scanning",
    "NetSecScan IP-Ranges, pot. used for Scanning",
    "Onyphe IP Ranges Used for Scanning",
    "List of published IP address ranges for Onyphe Scanner",
    "List of known IP address ranges for Palo Alto Networks Cortex Xpanse",
    "Probethenet IP Ranges Used for Scanning",
    "Rapid7 IP Ranges Used for Scanning",
    "Research scanner IP Ranges Used for Scanning",
    "Shadowforce IP Ranges Used for Scanning",
    "Shadowforce IP-Ranges, pot. used for Scanning",
    "Shadowserver IP-Ranges, pot. used for Scanning",
    "Shadowserver IP Ranges Used for Scanning",
    "Shodan IP Ranges Used for Scanning",
    "Shodan IP-Ranges, pot. used for Scanning",
    "Skipa IP Ranges Used for Scanning",
    "Stretchoid IP Ranges Used for Scanning",
    "List of known Tenable Cloud Sensors IPv4",
    "List of known Tenable Cloud Sensors IPv6"
]