"""Constants related to STIX 2.1"""

# Properties
STIX_PROPERTY_ID = "id"
STIX_PROPERTY_TYPE = "type"
STIX_PROPERTY_RELATIONSHIP_TYPE = "relationship_type"
STIX_PROPERTY_SOURCE_REF = "source_ref"
STIX_PROPERTY_TARGET_REF = "target_ref"
STIX_PROPERTY_EXTENSIONS = "extensions"
STIX_PROPERTY_BUNDLE_OBJECTS = "objects"
STIX_PROPERTY_X509_V3_EXTENSIONS = "x509_v3_extensions"
STIX_PROPERTY_CREATED = "created"
STIX_PROPERTY_MODIFIED = "modified"
STIX_PROPERTY_MARKING_DEF_DEFINITION = "definition"

# Value Types
TIMESTAMP_DATE_SEPARATOR = "-"
TIMESTAMP_DATE_TIME_SEPARATOR = "T"
TIMESTAMP_TIME_SEPARATOR = ":"
TIMESTAMP_MILLIS_SEPARATOR = "."
TIMESTAMP_ENDING = "Z"
STIX_TIMESTAMP_REGEX = (
    r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.\d+)?Z$"
)
