settings:
  digits: 3
  itemformat: markdown
  prefix: MRS
  sep: '-'

attributes:
  defaults:
    type: 'F'
    importance: "5"
    urgency: "5"
    vm: 'T'
    acceptance-criteria: |
      Successful validation according to the
      corresponding test case specification
    release: "Alpha"
    text: |
      # Title

      Description

      ### Rationale
      ...

  publish:
    - type
    - importance
    - urgency
    - vm
    - release
  
  reviewed:
    - type
    - importance
    - urgency
    - vm
    - release